### ISSUE TITLE
Parse formatted tables returned by HERE CLI version 1.1.0+

### ISSUE THREAD

**Issue by FelixVanOost** [FelixVanOost/Strava-Analysis-Tool#35]
**Summary**
The nicely-formatted data tables returned by release 1.1.0 onwards of the [HERE CLI](https://www.here.xyz/cli/cli/) contain UTF-8 characters that are not handled by the tool, causing an error when trying to upload a geo data file to HERE XYZ. The tool should be updated to handle the formatting used in newer releases of the HERE CLI.

**Steps to reproduce**
1. Ensure that the currently installed HERE CLI is **version 1.0.2 or older** using the command `here -V` in a terminal window. 
2. Run the tool with the command line argument `-gu` (generate and upload geospatial data).

**Observed behaviour**
The HERE XYZ upload process will fail with the following traceback:

```
Traceback (most recent call last):
  File "run.py", line 83, in <module>
    main()
  File "run.py", line 74, in main
    here_xyz.upload_geo_data(STRAVA_GEO_DATA_FILE)
  File "C:\Users\Felix\Documents\GitHub\Strava-Heatmap-Tool\here_xyz.py", line 76, in upload_geo_data
    space_id = _get_space_id()
  File "C:\Users\Felix\Documents\GitHub\Strava-Heatmap-Tool\here_xyz.py", line 35, in _get_space_id
    line = process.stdout.readline()
  File "C:\Users\Felix\Anaconda3\envs\Felix\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 359: character maps to <undefined>
```

**Expected behaviour**
The tool should correctly parse the output from newer releases of the HERE CLI and upload the geo data file as normal.

**Comment by FelixVanOost** [comment]
Bug fixed in PR #36.
