### ISSUE TITLE
ValueError with data without commutes

### ISSUE THREAD

**Issue by jac08h** [FelixVanOost/Strava-Analysis-Tool#60]
**ValueError with data without commutes**
When there are no commute data, correct summary is show but the application produces the ValueError

```
*Correct summary output*

Analysis: No commutes found
/home/jh/Strava-Analysis-Tool/venv/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py:1099: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  warnings.warn(
Traceback (most recent call last):
  File "strava_analysis_tool.py", line 101, in <module>
    main()
  File "strava_analysis_tool.py", line 93, in main
    analysis.display_commute_plots(activity_dataframe)
  File "/home/jh/SAT/analysis.py", line 331, in display_commute_plots
    _generate_commute_count_plot(commute_data, ax3, colours)
  File "/home/jh/SAT/analysis.py", line 99, in _generate_commute_count_plot
    sns.barplot(x=data.index.to_period('M'),
  File "/home/jh/Strava-Analysis-Tool/venv/lib/python3.8/site-packages/seaborn/categorical.py", line 3147, in barplot
    plotter = _BarPlotter(x, y, hue, data, order, hue_order,
  File "/home/jh/Strava-Analysis-Tool/venv/lib/python3.8/site-packages/seaborn/categorical.py", line 1616, in __init__
    self.establish_colors(color, palette, saturation)
  File "/home/jh/Strava-Analysis-Tool/venv/lib/python3.8/site-packages/seaborn/categorical.py", line 316, in establish_colors
    lum = min(light_vals) * .6
ValueError: min() arg is an empty sequence
```

**Steps to reproduce**
1. $ python strava_analysis_tool.py

**Comment by FelixVanOost** [comment]
Fixed in PR #61. Thanks, @jac08h!
